create table public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  company text not null check (char_length(company) between 1 and 120),
  role text not null check (char_length(role) between 1 and 160),
  stage text not null default 'Applied'
    check (stage in ('Saved', 'Applied', 'Interview', 'Offer', 'Rejected')),
  location text not null default '',
  job_url text not null default '',
  notes text not null default '',
  salary text not null default '',
  source text not null default '',
  contact text not null default '',
  interview_date timestamptz,
  deadline date,
  next_action text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  application_id bigint not null references public.applications (id) on delete cascade,
  event_type text not null,
  event_text text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index applications_user_updated_idx
  on public.applications (user_id, updated_at desc);

create index activities_user_application_idx
  on public.activities (user_id, application_id, created_at desc);

create index activities_application_id_idx
  on public.activities (application_id);

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger applications_set_updated_at
before update on public.applications
for each row execute function public.set_updated_at();

alter table public.applications enable row level security;
alter table public.activities enable row level security;

create policy "Users can view their applications"
on public.applications
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their applications"
on public.applications
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their applications"
on public.applications
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their applications"
on public.applications
for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can view their activities"
on public.activities
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create activities for their applications"
on public.activities
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.applications
    where applications.id = activities.application_id
      and applications.user_id = (select auth.uid())
  )
);

create policy "Users can delete their activities"
on public.activities
for delete
to authenticated
using ((select auth.uid()) = user_id);

revoke all on public.applications, public.activities from anon;
grant select, insert, update, delete on public.applications to authenticated;
grant select, insert, delete on public.activities to authenticated;
grant usage, select on sequence public.applications_id_seq to authenticated;
grant usage, select on sequence public.activities_id_seq to authenticated;

revoke execute on function public.set_updated_at() from public, anon, authenticated;
